addpath(genpath(pwd));
addpath(genpath("src"));
cfg_params_and_run_v35

turbo_results_dashboard_ui_v35("modelPath","turbo_model_v35.mat", ...
  "extInput","input.mat","extOutput","output.mat", ...
  "predictFcn","predict_turbocompressor_model_v35", ...
  "speedIdx",1);